#Default fake action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo-token:
    description: Repository token needed
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'

