name: Reopen closed issues
on:
  issues:
    types: [ closed ]
   #issue_comment:
     #types: [ created, edited ] # only for debug purposes!
jobs:
  reopen_dependent_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Block Closing Dependent Issue
      uses: ./ # Uses an action in the root directory
      id: autoissuebot
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
