name: Reopen closed issues
on:
  issues:
    types: [ closed ] 
jobs:
  maybe_reopen_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Block Closing Dependent Issue
      uses: ./ # Uses an action in the root directory
      id: autoissuebot
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
